version: '3.7'

services:
  web:
    build: .
#    command: pwd
    command: python ./controller/StockResource.py run -h 0.0.0.0
    volumes:
      - . :/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev